server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
mybatis-plus:
  configuration:
    default-fetch-size: 10000
    default-statement-timeout: 300
  type-aliases-package: com.example.project.entity
